name: Build and deploy Virtual Visits (Docker)

on:
  push:
    branches:
      - azure

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: "Login to Azure via CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and publish Docker image to Azure Container Registry"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_INITIAL_TEMPLATE_ID: ${{ secrets.EMAIL_INITIAL_TEMPLATE_ID }}
          EMAIL_JOIN_TEMPLATE_ID: ${{ secrets.EMAIL_JOIN_TEMPLATE_ID }}
          EMAIL_UPDATED_VISIT_TEMPLATE_ID: ${{ secrets.EMAIL_UPDATED_VISIT_TEMPLATE_ID }}
          SMS_INITIAL_TEMPLATE_ID: ${{ secrets.SMS_INITIAL_TEMPLATE_ID }}
          SMS_JOIN_TEMPLATE_ID: ${{ secrets.SMS_JOIN_TEMPLATE_ID }}
          SMS_UPDATED_VISIT_TEMPLATE_ID: ${{ secrets.SMS_UPDATED_VISIT_TEMPLATE_ID }}
      - run: |
          echo "API KEY SIZE: ${#API_KEY}"
          bin/write_environment.sh
          docker build . -t ${{ secrets.ACR_SERVER }}/virtualvisits:${{ github.sha }}
          docker push ${{ secrets.ACR_SERVER }}/virtualvisits:${{ github.sha }}

      # - name: "Deploy Docker iamge to Azure App Service"
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'virtualvisitsdocker'
      #     images: '${{ secrets.ACR_SERVER }}/virtualvisits:${{ github.sha }}'
